modLoader = "javafml"
loaderVersion = "[46,)"
license = "All right reserved"

[[mods]]
    modId = "armortrimitemfix"
    version = "${file.jarVersion}"
    displayName = "${mod_name}"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://curseforge.com/minecraft/mc-mods/armor-trim-item-fix"
    issueTrackerURL="https://github.com/MincraftEinstein/ArmorTrimItemFix/issues"
    logoFile = "pack.png"
    credits = ""
    authors = "${mod_author}"
    displayTest = "IGNORE_ALL_VERSION"
    description = '''
Trimmed armor items in Minecraft display one of four generic trim textures for every item, no matter what trim you put on an item the texture is always the same. This mod fixes that by adding more item trim textures that change depending on the trim applied
'''

[[dependencies.armortrimitemfix]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.armortrimitemfix]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20, 1.21)"
    ordering = "NONE"
    side = "BOTH"
