modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "All right reserved"
issueTrackerURL="https://github.com/MincraftEinstein/ArmorTrimItemFix/issues"

[[mods]]
    modId = "armortrimitemfix"
    version = "${version}"
    displayName = "Armor Trim Item Fix"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL = "https://curseforge.com/minecraft/mc-mods/armor-trim-item-fix"
    logoFile = "pack.png"
    authors = "${mod_author}"
    description = "${description}"
    displayTest = "IGNORE_ALL_VERSION"

[[dependencies.armortrimitemfix]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version}"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.armortrimitemfix]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minecraft_version}, ${max_minecraft_version})"
    ordering = "NONE"
    side = "CLIENT"
