# Project
version=2.1.5
group=einstein.armortrimitemfix
java_version=25

# Common
minecraft_version=26.2
max_minecraft_version=26.3
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric
fabric_version=0.19.3
fabric_api_version=0.156.0+26.2
modmenu_version=20.0.1
fabric_more_trims_version=s6hJsf8C

# NeoForge
neoforge_version=26.2.0.41-beta
neoforge_loader_version_range=[4,)
neoforge_more_trims_version=9Ewg7LhM

# Mod options
mod_name=ArmorTrimItemFix
mod_author=MincraftEinstein
mod_id=armortrimitemfix
description=Trimmed armor items in Minecraft display one of four generic trim textures for every item, no matter what trim you put on an item the texture is always the same. This mod fixes that by adding more item trim textures that change depending on the trim applied

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
