# Project
version=1.2.0
group=einstein.armortrimitemfix
java_version=21

# Common
minecraft_version=1.20.1
max_minecraft_version=1.20.2

# Fabric
fabric_version=0.16.0
fabric_api_version=0.92.0+1.20.1
modmenu_version=7.2.2
fabric_more_trims_version=AQDvTm1D

# Forge
forge_version=47.3.0
forge_loader_version_range=[47,)

# Mod options
mod_name=ArmorTrimItemFix
mod_author=MincraftEinstein
mod_id=armortrimitemfix
description=Trimmed armor items in Minecraft display one of four generic trim textures for every item, no matter what trim you put on an item the texture is always the same. This mod fixes that by adding more item trim textures that change depending on the trim applied

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
