modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "All right reserved"
issueTrackerURL="https://github.com/MincraftEinstein/ArmorTrimItemFix/issues"

[[mods]]
    modId = "armortrimitemfix"
    version = "${version}"
    displayName = "Armor Trim Item Fix"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL = "https://curseforge.com/minecraft/mc-mods/armor-trim-item-fix"
    logoFile = "pack.png"
    authors = "${mod_author}"
    description = "${description}"

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies.armortrimitemfix]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforge_version}"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.armortrimitemfix]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version}, ${max_minecraft_version})"
    ordering = "NONE"
    side = "CLIENT"
